[package]
name = "seal-worker"
version = "0.1.0"
authors = ["PolkaX <https://github.com/PolkaX>"]
edition = "2018"

[dependencies]
log = "0.4"
structopt = "0.3"
thiserror = "1.0"
serde_json = "1.0"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
