[package]
name = "node-service"
version = "0.1.0"
authors = ["PolkaX <https://github.com/PolkaX>"]
edition = "2018"

[dependencies]
async-std = { version = "1.5", features = ["unstable"] }
ctrlc = "3.1"
exit-future = "0.2"
futures = "0.3"
thiserror = "1.0"

# node
repo = { path = "../repo" }
