[package]
name = "gen"
version = "0.1.0"
authors = ["PolkaX <https://github.com/PolkaX>"]
edition = "2018"

[dependencies]
anyhow = "1.0"

# plum
plum_address = { path = "../../../vendor/plum/primitives/address" }
plum_bigint = { path = "../../../vendor/plum/primitives/bigint" }
plum_crypto = { path = "../../../vendor/plum/crypto" }
plum_hashing = { path = "../../../vendor/plum/hashing" }
plum_tipset = { path = "../../../vendor/plum/primitives/tipset" }

# core
api = { path = "../api" }
sectorbuilder = { path = "../sectorbuilder" }
