[package]
name = "gen"
version = "0.1.0"
authors = ["PolkaX <https://github.com/PolkaX>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
byteorder = "1.3"
paired = "0.18.0"
sha2 = "0.8"

# plum
plum_bigint = { path = "../../../vendor/plum/primitives/bigint" }
sigs = { path = "../../../vendor/plum/sigs" }
types = { path = "../../../vendor/plum/chain/types" }
# core
api = { path = "../api", package = "rust-api" }
sectorbuilder = { path = "../sectorbuilder", package = "rust-sectorbuilder" }
