[package]
name = "gen"
version = "0.1.0"
authors = ["PolkaX <https://github.com/PolkaX>"]
edition = "2018"

[dependencies]
anyhow = "1.0"

# plum
plum_api_client = { path = "../../../vendor/plum/api-client" }
plum_address = { path = "../../../vendor/plum/primitives/address" }
plum_bigint = { path = "../../../vendor/plum/primitives/bigint" }
plum_block = { path = "../../../vendor/plum/primitives/block" }
plum_sector = { path = "../../../vendor/plum/primitives/sector" }
plum_crypto = { path = "../../../vendor/plum/primitives/crypto" }
plum_hashing = { path = "../../../vendor/plum/hashing" }
plum_tipset = { path = "../../../vendor/plum/primitives/tipset" }

# core
sectorbuilder = { path = "../sectorbuilder" }
