[package]
name = "miner"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
lru = "0.4"
bytes = "0.5"
anyhow = "1.0"
chrono = "0.4"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
# ipfs
cid = { package = "rust-cid", git = "https://github.com/PolkaX/rust-ipfs", branch = "filecoin-master", features = ["serde_support"] }
block_format = { package = "rust-block-format", git = "https://github.com/PolkaX/rust-ipfs", branch = "filecoin-master" }
serde_cbor = { git = "https://github.com/PolkaX/cbor", branch = "f64ser-hack", features = ["tags"] }
rust-ipld-cbor = { package = "rust-ipld-cbor", git = "https://github.com/PolkaX/rust-ipfs", branch = "filecoin-master", features = ["bigint"] }
# plum
types = { path = "../../../vendor/plum/chain/types" }
plum_bigint = { path = "../../../vendor/plum/chain/bigint" }
# local
api = { package = "rust-api", path = "../api" }
gen = { package = "gen", path = "../gen" }
