[workspace]
members = [
    "bin/seal-worker",
    "bin/storage-miner",
    "core/api",
    "core/sectorbuilder",
    "core/state_machine",
    "core/miner",
    "core/gen",
    "node/config",
    "node/repo",
    "node/utils",
    "node/service",
    "node/paramfetch",
]
