[package]
name = "seal-seed"
version = "0.1.0"
authors = ["PolkaX"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plum_address = { path = "../../../vendor/plum/primitives/address" }
plum_wallet = { path = "../../../vendor/plum/wallet" }
sectorbuilder = { path = "../../core/sectorbuilder" }
repo = { path = "../../node/repo" }
utils = { path = "../../common/utils" }
ds-rocksdb = { git = "https://github.com/PolkaX/rust-ipfs", branch = "filecoin-master" }
