[package]
name = "seal-seed"
version = "0.1.0"
authors = ["PolkaX"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plum_address = { path = "../../../vendor/plum/primitives/address" }
plum_sector = { path = "../../../vendor/plum/primitives/sector" }
plum_wallet = { path = "../../../vendor/plum/wallet" }
repo = { path = "../../node/repo" }
utils = { path = "../../common/utils" }
proof_wrapper = { path = "../../core/sector-storage/proof_wrapper" }
specs-storage = { path = "../../core/sector-storage/specs-storage" }
ds-rocksdb = { git = "https://github.com/PolkaX/rust-ipfs", branch = "filecoin-master" }
filecoin-proofs-api = { git = "https://github.com/filecoin-project/rust-filecoin-proofs-api" }
rand_xorshift = "0.2.0"
rand = "0.7"
tempfile = "3"
