[package]
name = "storage-miner"
version = "0.1.0"
authors = ["PolkaX <https://github.com/PolkaX>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
exit-future = "0.2"
futures = "0.3"

datastore = { package = "rust-datastore", git = "https://github.com/PolkaX/rust-ipfs", branch = "filecoin-master" }
ds-rocksdb = { package = "rust-ds-rocksdb", git = "https://github.com/PolkaX/rust-ipfs", branch = "filecoin-master" }

api = { package = "rust-api", path = "../../core/api" }
sector-builder = { package = "rust-sectorbuilder", path = "../../core/sectorbuilder" }
node-service = { path = "../../node/service" }