[package]
name = "storage-miner"
version = "0.1.0"
authors = ["PolkaX <https://github.com/PolkaX>"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
async-std = { version = "1.5", features = ["unstable"] }
atty = "0.2.13"
dirs = "2.0"
env_logger = "0.7.0"
exit-future = "0.2"
futures = "0.3"
futures-diagnose = "1.0"
lazy_static = "1.4.0"
log = "0.4"
regex = "1.3.1"
time = "0.1.42"
serde_json = "1.0"
structopt = "0.3"
thiserror = "1.0"

# ipfs
datastore = { package = "rust-datastore", git = "https://github.com/PolkaX/rust-ipfs", branch = "filecoin-master" }
ds-rocksdb = { package = "rust-ds-rocksdb", git = "https://github.com/PolkaX/rust-ipfs", branch = "filecoin-master" }
# plum
plum_address = { path = "../../../vendor/plum/primitives/address" }
# core
sectorbuilder = { package = "rust-sectorbuilder", path = "../../core/sectorbuilder" }
# node
node-service = { path = "../../node/service" }
repo = { path = "../../node/repo" }
node-utils = { path = "../../node/utils" }
node-config = { path = "../../node/config" }
node-paramfetch = { path = "../../node/paramfetch" }
