[package]
name = "rust-api"
version = "0.1.0"
authors = ["PolkaX <https://github.com/PolkaX>"]
edition = "2018"

[dependencies]
anyhow = "1.0"

# plum
types = { path = "../../../vendor/plum/chain/types" }
plum_bigint = { path = "../../../vendor/plum/primitives/bigint" }
