[package]
name = "gen"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
api = { package = "rust-api", path = "../api" }
types = { package = "types", git = "https://github.com/PolkaX/plum" }
