[package]
name = "gen"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.8"
anyhow = "1.0"
paired = { version = "0.18.0" }
byteorder = "1.3"
api = { path = "../api", package = "rust-api" }
sigs = { git = "https://github.com/PolkaX/plum", package = "sigs" }
types = { git = "https://github.com/PolkaX/plum", package = "types" }

sectorbuilder = { path = "../sectorbuilder", package = "rust-sectorbuilder" }
